// package exceptiontest;
// //try 블록 안에 두개의 예외 가 발생하도록 한후 TRY블록 안에서 발생하는 모든 예외를 처리 할수 있도로 catch 구문을 구성
// public class Test6 {
//     public static void main(String[] args){

//     int a = 5;
//     int b = 0;
//     int c;
//     int A[] = new int[3];

//     try {

//         c = a/b;
//         A[3] = 100;
    
//     } catch (AException e) {
//        System.out.println("0 으로 나눌수 없다");
//     }catch(BException e){
//         System.out.println("없는 인덱스이다");
//     }
//     finally{
//         System.out.println("finally 구문");
//     }
// }
    
// }
